version: '3'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_COLLECTION_ENABLED: "true"
      XPACK_SECURITY_ENABLED: "false"

    ports:
      - 5601:5601
    networks:
      - elasticsearch
    depends_on: 
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.13.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=true
    volumes:
    - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch

  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - elasticsearch
      
volumes: 
  elastic:
  redis:
networks:
  elasticsearch:

    