version: '3'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    networks:
      - elasticsearch
    depends_on: 
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
    - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch
      
volumes: 
  elastic:
networks:
  elasticsearch:

    